// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/course.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace EposeaLocalBackend.gRPC.Course {
  public static partial class Courser
  {
    static readonly string __ServiceName = "course.Courser";

    static readonly grpc::Marshaller<global::EposeaLocalBackend.gRPC.Course.GetCoursesRequest> __Marshaller_course_GetCoursesRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EposeaLocalBackend.gRPC.Course.GetCoursesRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::EposeaLocalBackend.gRPC.Course.CourseDto> __Marshaller_course_CourseDto = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EposeaLocalBackend.gRPC.Course.CourseDto.Parser.ParseFrom);

    static readonly grpc::Method<global::EposeaLocalBackend.gRPC.Course.GetCoursesRequest, global::EposeaLocalBackend.gRPC.Course.CourseDto> __Method_GetCourses = new grpc::Method<global::EposeaLocalBackend.gRPC.Course.GetCoursesRequest, global::EposeaLocalBackend.gRPC.Course.CourseDto>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetCourses",
        __Marshaller_course_GetCoursesRequest,
        __Marshaller_course_CourseDto);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::EposeaLocalBackend.gRPC.Course.CourseReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Courser</summary>
    [grpc::BindServiceMethod(typeof(Courser), "BindService")]
    public abstract partial class CourserBase
    {
      public virtual global::System.Threading.Tasks.Task GetCourses(global::EposeaLocalBackend.gRPC.Course.GetCoursesRequest request, grpc::IServerStreamWriter<global::EposeaLocalBackend.gRPC.Course.CourseDto> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CourserBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetCourses, serviceImpl.GetCourses).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CourserBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetCourses, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::EposeaLocalBackend.gRPC.Course.GetCoursesRequest, global::EposeaLocalBackend.gRPC.Course.CourseDto>(serviceImpl.GetCourses));
    }

  }
}
#endregion
